# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

def firebase
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Crashlytics'
end

def auth
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
end

def google_apiclient
  pod 'GoogleAPIClientForREST'
end

def maps
  pod 'GoogleMaps'
end

def lottie
  pod 'lottie-ios'
end

def dotzu
  pod 'Dotzu', :configurations => ['Debug']
end

def test_pods
  pod 'Quick'
  pod 'Nimble'
end

target 'app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app

end

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
#  firebase
#  auth
#  google_apiclient
#  maps
#  lottie

  pod 'DIKit', '~> 1.0.0'
#  pod 'MaterialComponents'
  pod 'SwiftLint'
#  pod 'YouTubePlayer', :git => 'https://github.com/weakfl/Swift-YouTube-Player'
  pod 'AlamofireImage'
#  pod 'GoogleMobileVision'
#  pod 'GoogleAPIClientForREST/Calendar'

  target 'iosAppTests' do
    inherit! :search_paths
    # Pods for testing
    test_pods
  end
  
  target 'iosAppUITests' do
    inherit! :search_paths
  end

end
